name: Deploy to DigitalOcean Spaces

on: push

permissions:
  contents: write

jobs:
  deploy-spaces:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install dependencies, test, and build
      run: |
        npm ci
        npm test
        npm run build

    - name: Deploy DNS lookup commit to DigitalOcean Spaces
      run: aws s3 sync ./dist/dns-lookup s3://${{ secrets.SPACES_BUCKET }}/commits/dns-lookup/${{ github.sha }} --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com --acl public-read --content-encoding utf8
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SPACES_REGION }}

    - name: Deploy SPF explainer commit to DigitalOcean Spaces
      run: aws s3 sync ./dist/spf-explainer s3://${{ secrets.SPACES_BUCKET }}/commits/spf-explainer/${{ github.sha }} --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com --acl public-read --content-encoding utf8
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SPACES_REGION }}

    - name: Leave a comment on commit
      run: npm run deploy:spaces:comment
      env:
        REPO_NAME: ${{ github.repository }}
        COMMIT_SHA: ${{ github.sha }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SPACES_REGION: ${{ secrets.SPACES_REGION }}
        SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }}
